name: Perl CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Perl setup
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
        
      # Runs a single command using the runners shell
      - name: Install of perl module
        run: cpanm --notest Test::More File::Temp IPC::Open3

      # Runs a set of commands using the runners shell
      - name: Runs unit test and end-to-end test
        run: prove -lv t/*.t
